AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Movie-app

  Sample SAM Template for Movie-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  MoviesTableName:
    Default: movies-table
    Type: String

Resources:
  MoviesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: movies-table
      AttributeDefinitions:
        - AttributeName: movieId
          AttributeType: S
      KeySchema:
        - AttributeName: movieId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  AddMovie:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: movie-service/
      Handler: app.addMovie
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MoviesTable
      Environment:
        Variables:
          TABLE_NAME: !Ref MoviesTable
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /movie
            Method: POST

  GetMovie:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: movie-service/
      Handler: app.getMovie
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MoviesTable
      Environment:
        Variables:
          TABLE_NAME: !Ref MoviesTable
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /movie
            Method: GET
# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for Movie Service function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/movie/"
#   MovieServiceFunction:
#     Description: "Movie Service Lambda Function ARN"
#     Value: !GetAtt MovieServiceFunction.Arn
#   MovieServiceFunctionIamRole:
#     Description: "Implicit IAM Role created for Movie Service function"
#     Value: !GetAtt MovieServiceFunctionRole.Arn
